import type { CommunityRegion, Question, TestMeta } from "./types";

const viajerosAlmeriaTests: TestMeta[] = [
  { id: "viajeros_almeria_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_almeria_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_almeria_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_almeria_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_almeria_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_almeria_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_almeria_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_almeria_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_almeria_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_almeria_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_almeria_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_almeria_noviembre_2025", name: "Noviembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_almeria_enero_2026", name: "Enero 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_almeria_marzo_2026", name: "Marzo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_almeria_mayo_2026", name: "Mayo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_almeria_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosCadizTests: TestMeta[] = [
  { id: "viajeros_cadiz_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_cadiz_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_cadiz_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_cadiz_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_cadiz_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_cadiz_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_cadiz_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_cadiz_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_cadiz_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_cadiz_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_cadiz_enero_2026", name: "Enero 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_cadiz_marzo_2026", name: "Marzo 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_cadiz_mayo_2026", name: "Mayo 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_cadiz_julio_2026", name: "Julio 2026", img: "/img/bus2.jpg" },
];

const viajerosCordobaTests: TestMeta[] = [
  { id: "viajeros_cordoba_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_cordoba_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_cordoba_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_cordoba_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_cordoba_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_cordoba_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_cordoba_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_cordoba_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_cordoba_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_cordoba_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_cordoba_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_cordoba_noviembre_2025", name: "Noviembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_cordoba_enero_2026", name: "Enero 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_cordoba_marzo_2026", name: "Marzo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_cordoba_mayo_2026", name: "Mayo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_cordoba_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosGranadaTests: TestMeta[] = [
  { id: "viajeros_granada_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_granada_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_granada_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_granada_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_granada_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_granada_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_granada_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_granada_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_granada_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_granada_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_granada_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_granada_noviembre_2025", name: "Noviembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_granada_enero_2026", name: "Enero 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_granada_marzo_2026", name: "Marzo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_granada_mayo_2026", name: "Mayo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_granada_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosHuelvaTests: TestMeta[] = [
  { id: "viajeros_huelva_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_huelva_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_huelva_noviembre_2025", name: "Noviembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_huelva_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosJaenTests: TestMeta[] = [
  { id: "viajeros_jaen_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_jaen_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_jaen_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_jaen_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_jaen_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_jaen_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_jaen_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_jaen_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_jaen_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_jaen_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_jaen_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_jaen_noviembre_2025", name: "Noviembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_jaen_enero_2026", name: "Enero 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_jaen_marzo_2026", name: "Marzo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_jaen_mayo_2026", name: "Mayo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_jaen_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosMalagaTests: TestMeta[] = [
  { id: "viajeros_malaga_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_malaga_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_malaga_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_malaga_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_malaga_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_malaga_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_malaga_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_malaga_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_malaga_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_malaga_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_malaga_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_malaga_enero_2026", name: "Enero 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_malaga_marzo_2026", name: "Marzo 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_malaga_mayo_2026", name: "Mayo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_malaga_julio_2026", name: "Julio 2026", img: "/img/bus3.jpg" },
];

const viajerosSevillaTests: TestMeta[] = [
  { id: "viajeros_sevilla_enero_2024", name: "Enero 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_sevilla_marzo_2024", name: "Marzo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_sevilla_mayo_2024", name: "Mayo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_sevilla_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_sevilla_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_sevilla_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_sevilla_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_sevilla_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_sevilla_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_sevilla_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_sevilla_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_sevilla_noviembre_2025", name: "Noviembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_sevilla_enero_2026", name: "Enero 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_sevilla_marzo_2026", name: "Marzo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_sevilla_mayo_2026", name: "Mayo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_sevilla_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosCatalunaTests: TestMeta[] = [
  { id: "viajeros_cataluna_marzo_2023", name: "Marzo 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_cataluna_mayo_2023", name: "Mayo 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_cataluna_julio_2023", name: "Julio 2023", img: "/img/bus3.jpg" },
  { id: "viajeros_cataluna_septiembre_2023", name: "Septiembre 2023", img: "/img/bus4.jpg" },
  { id: "viajeros_cataluna_noviembre_2023", name: "Noviembre 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_cataluna_enero_2024", name: "Enero 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_cataluna_marzo_2024", name: "Marzo 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_cataluna_mayo_2024", name: "Mayo 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_cataluna_julio_2024", name: "Julio 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_cataluna_septiembre_2024", name: "Septiembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_cataluna_noviembre_2024", name: "Noviembre 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_cataluna_enero_2025", name: "Enero 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_cataluna_marzo_2025", name: "Marzo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_cataluna_mayo_2025", name: "Mayo 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_cataluna_julio_2025", name: "Julio 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_cataluna_septiembre_2025", name: "Septiembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_cataluna_noviembre_2025", name: "Noviembre 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_cataluna_enero_2026", name: "Enero 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_cataluna_marzo_2026", name: "Marzo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_cataluna_mayo_2026", name: "Mayo 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_cataluna_julio_2026", name: "Julio 2026", img: "/img/bus1.jpg" },
];

const viajerosValenciaTests: TestMeta[] = [
  { id: "viajeros_valencia_enero_2023", name: "Enero 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_valencia_marzo_2023", name: "Marzo 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_valencia_mayo_2023", name: "Mayo 2023", img: "/img/bus3.jpg" },
  { id: "viajeros_valencia_julio_2023", name: "Julio 2023", img: "/img/bus4.jpg" },
  { id: "viajeros_valencia_septiembre_2023", name: "Septiembre 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_valencia_noviembre_2023", name: "Noviembre 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_valencia_enero_2024", name: "Enero 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_valencia_marzo_2024", name: "Marzo 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_valencia_mayo_2024", name: "Mayo 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_valencia_julio_2024", name: "Julio 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_valencia_septiembre_2024", name: "Septiembre 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_valencia_noviembre_2024", name: "Noviembre 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_valencia_febrero_2025", name: "Febrero 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_valencia_abril_2025", name: "Abril 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_valencia_mayo_2025", name: "Mayo 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_valencia_julio_2025", name: "Julio 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_valencia_septiembre_2025", name: "Septiembre 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_valencia_noviembre_2025", name: "Noviembre 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_valencia_febrero_2026", name: "Febrero 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_valencia_marzo_2026", name: "Marzo 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_valencia_mayo_2026", name: "Mayo 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_valencia_julio_2026", name: "Julio 2026", img: "/img/bus2.jpg" },
];

const viajerosCantabriaTests: TestMeta[] = [
  { id: "viajeros_cantabria_febrero_2025", name: "Febrero 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_cantabria_abril_2025", name: "Abril 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_cantabria_junio_2025", name: "Junio 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_cantabria_agosto_2025", name: "Agosto 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_cantabria_octubre_2025", name: "Octubre 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_cantabria_diciembre_2025", name: "Diciembre 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_cantabria_febrero_2026", name: "Febrero 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_cantabria_abril_2026", name: "Abril 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_cantabria_junio_2026", name: "Junio 2026", img: "/img/bus1.jpg" },
];

const viajerosAlavaTests: TestMeta[] = [
  { id: "viajeros_alava_febrero_2023", name: "Febrero 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_alava_marzo_2023", name: "Marzo 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_alava_junio_2023", name: "Junio 2023", img: "/img/bus3.jpg" },
  { id: "viajeros_alava_julio_2023", name: "Julio 2023", img: "/img/bus4.jpg" },
  { id: "viajeros_alava_septiembre_2023", name: "Septiembre 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_alava_noviembre_2023", name: "Noviembre 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_alava_febrero_2024", name: "Febrero 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_alava_marzo_2024", name: "Marzo 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_alava_mayo_2024", name: "Mayo 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_alava_julio_2024", name: "Julio 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_alava_septiembre_2024", name: "Septiembre 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_alava_noviembre_2024", name: "Noviembre 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_alava_enero_2025", name: "Enero 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_alava_marzo_2025", name: "Marzo 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_alava_mayo_2025", name: "Mayo 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_alava_julio_2025", name: "Julio 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_alava_septiembre_2025", name: "Septiembre 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_alava_noviembre_2025", name: "Noviembre 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_alava_enero_2026", name: "Enero 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_alava_marzo_2026", name: "Marzo 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_alava_mayo_2026", name: "Mayo 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_alava_julio_2026", name: "Julio 2026", img: "/img/bus2.jpg" },
];

const viajerosGuipuzkoaTests: TestMeta[] = [
  { id: "viajeros_guipuzkoa_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_guipuzkoa_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_guipuzkoa_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_guipuzkoa_noviembre_2025", name: "Noviembre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_guipuzkoa_enero_2026", name: "Enero 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_guipuzkoa_marzo_2026", name: "Marzo 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_guipuzkoa_mayo_2026", name: "Mayo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_guipuzkoa_julio_2026", name: "Julio 2026", img: "/img/bus4.jpg" },
];

const viajerosGaliciaTests: TestMeta[] = [
  { id: "viajeros_galicia_enero_2023", name: "Enero 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_marzo_2023", name: "Marzo 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_junio_2023", name: "Junio 2023", img: "/img/bus3.jpg" },
  { id: "viajeros_galicia_julio_2023", name: "Julio 2023", img: "/img/bus4.jpg" },
  { id: "viajeros_galicia_septiembre_2023", name: "Septiembre 2023", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_octubre_2023", name: "Octubre 2023", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_noviembre_2023", name: "Noviembre 2023", img: "/img/bus3.jpg" },
  { id: "viajeros_galicia_enero_2024", name: "Enero 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_galicia_marzo_2024", name: "Marzo 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_mayo_2024", name: "Mayo 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_junio_2024", name: "Junio 2024", img: "/img/bus3.jpg" },
  { id: "viajeros_galicia_julio_2024", name: "Julio 2024", img: "/img/bus4.jpg" },
  { id: "viajeros_galicia_septiembre_2024", name: "Septiembre 2024", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_noviembre_2024", name: "Noviembre 2024", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_enero_2025", name: "Enero 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_galicia_marzo_2025", name: "Marzo 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_galicia_mayo_2025", name: "Mayo 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_julio_2025", name: "Julio 2025", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_septiembre_2025", name: "Septiembre 2025", img: "/img/bus3.jpg" },
  { id: "viajeros_galicia_octubre_2025", name: "Octubre 2025", img: "/img/bus4.jpg" },
  { id: "viajeros_galicia_noviembre_2025", name: "Noviembre 2025", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_enero_2026", name: "Enero 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_marzo_2026", name: "Marzo 2026", img: "/img/bus3.jpg" },
  { id: "viajeros_galicia_mayo_2026", name: "Mayo 2026", img: "/img/bus4.jpg" },
  { id: "viajeros_galicia_junio_2026", name: "Junio 2026", img: "/img/bus1.jpg" },
  { id: "viajeros_galicia_julio_2026", name: "Julio 2026", img: "/img/bus2.jpg" },
  { id: "viajeros_galicia_septiembre_2026", name: "Septiembre 2026", img: "/img/bus3.jpg" },
];

const viajerosExtremaduraTests: TestMeta[] = [
];

const viajerosMurciaTests: TestMeta[] = [
];

export const viajerosCommunityRegions: CommunityRegion[] = [
  {
    id: "andalucia",
    name: "Andalucía",
    tests: [],
    subregions: [
      { id: "almeria", name: "Almería", tests: viajerosAlmeriaTests },
      { id: "cadiz", name: "Cádiz", tests: viajerosCadizTests },
      { id: "cordoba", name: "Córdoba", tests: viajerosCordobaTests },
      { id: "granada", name: "Granada", tests: viajerosGranadaTests },
      { id: "huelva", name: "Huelva", tests: viajerosHuelvaTests },
      { id: "jaen", name: "Jaén", tests: viajerosJaenTests },
      { id: "malaga", name: "Málaga", tests: viajerosMalagaTests },
      { id: "sevilla", name: "Sevilla", tests: viajerosSevillaTests },
    ],
  },
  { id: "cataluna", name: "Cataluña", tests: viajerosCatalunaTests },
  { id: "valencia", name: "Valencia", tests: viajerosValenciaTests },
  { id: "cantabria", name: "Cantabria", tests: viajerosCantabriaTests },
  {
    id: "pais_vasco",
    name: "País Vasco",
    tests: [],
    subregions: [
      { id: "alava", name: "Álava", tests: viajerosAlavaTests },
      { id: "guipuzkoa", name: "Guipúzcoa", tests: viajerosGuipuzkoaTests },
      { id: "vizcaya", name: "Vizcaya", tests: [] },
    ],
  },
  { id: "galicia", name: "Galicia", tests: viajerosGaliciaTests },
  { id: "extremadura", name: "Extremadura", tests: viajerosExtremaduraTests },
  { id: "murcia", name: "Murcia", tests: viajerosMurciaTests },
];

export const viajerosExamLoaders: Record<
  string,
  () => Promise<{ default: Question[] }>
> = {
  viajeros_alava_enero_2025: () => import("@/data/exams/viajeros_alava_enero_2025.json"),
  viajeros_alava_enero_2026: () => import("@/data/exams/viajeros_alava_enero_2026.json"),
  viajeros_alava_febrero_2023: () => import("@/data/exams/viajeros_alava_febrero_2023.json"),
  viajeros_alava_febrero_2024: () => import("@/data/exams/viajeros_alava_febrero_2024.json"),
  viajeros_alava_julio_2023: () => import("@/data/exams/viajeros_alava_julio_2023.json"),
  viajeros_alava_julio_2024: () => import("@/data/exams/viajeros_alava_julio_2024.json"),
  viajeros_alava_julio_2025: () => import("@/data/exams/viajeros_alava_julio_2025.json"),
  viajeros_alava_julio_2026: () => import("@/data/exams/viajeros_alava_julio_2026.json"),
  viajeros_alava_junio_2023: () => import("@/data/exams/viajeros_alava_junio_2023.json"),
  viajeros_alava_marzo_2023: () => import("@/data/exams/viajeros_alava_marzo_2023.json"),
  viajeros_alava_marzo_2024: () => import("@/data/exams/viajeros_alava_marzo_2024.json"),
  viajeros_alava_marzo_2025: () => import("@/data/exams/viajeros_alava_marzo_2025.json"),
  viajeros_alava_marzo_2026: () => import("@/data/exams/viajeros_alava_marzo_2026.json"),
  viajeros_alava_mayo_2024: () => import("@/data/exams/viajeros_alava_mayo_2024.json"),
  viajeros_alava_mayo_2025: () => import("@/data/exams/viajeros_alava_mayo_2025.json"),
  viajeros_alava_mayo_2026: () => import("@/data/exams/viajeros_alava_mayo_2026.json"),
  viajeros_alava_noviembre_2023: () => import("@/data/exams/viajeros_alava_noviembre_2023.json"),
  viajeros_alava_noviembre_2024: () => import("@/data/exams/viajeros_alava_noviembre_2024.json"),
  viajeros_alava_noviembre_2025: () => import("@/data/exams/viajeros_alava_noviembre_2025.json"),
  viajeros_alava_septiembre_2023: () => import("@/data/exams/viajeros_alava_septiembre_2023.json"),
  viajeros_alava_septiembre_2024: () => import("@/data/exams/viajeros_alava_septiembre_2024.json"),
  viajeros_alava_septiembre_2025: () => import("@/data/exams/viajeros_alava_septiembre_2025.json"),
  viajeros_almeria_enero_2024: () => import("@/data/exams/viajeros_almeria_enero_2024.json"),
  viajeros_almeria_enero_2025: () => import("@/data/exams/viajeros_almeria_enero_2025.json"),
  viajeros_almeria_enero_2026: () => import("@/data/exams/viajeros_almeria_enero_2026.json"),
  viajeros_almeria_julio_2024: () => import("@/data/exams/viajeros_almeria_julio_2024.json"),
  viajeros_almeria_julio_2025: () => import("@/data/exams/viajeros_almeria_julio_2025.json"),
  viajeros_almeria_julio_2026: () => import("@/data/exams/viajeros_almeria_julio_2026.json"),
  viajeros_almeria_marzo_2024: () => import("@/data/exams/viajeros_almeria_marzo_2024.json"),
  viajeros_almeria_marzo_2025: () => import("@/data/exams/viajeros_almeria_marzo_2025.json"),
  viajeros_almeria_marzo_2026: () => import("@/data/exams/viajeros_almeria_marzo_2026.json"),
  viajeros_almeria_mayo_2024: () => import("@/data/exams/viajeros_almeria_mayo_2024.json"),
  viajeros_almeria_mayo_2025: () => import("@/data/exams/viajeros_almeria_mayo_2025.json"),
  viajeros_almeria_mayo_2026: () => import("@/data/exams/viajeros_almeria_mayo_2026.json"),
  viajeros_almeria_noviembre_2024: () => import("@/data/exams/viajeros_almeria_noviembre_2024.json"),
  viajeros_almeria_noviembre_2025: () => import("@/data/exams/viajeros_almeria_noviembre_2025.json"),
  viajeros_almeria_septiembre_2024: () => import("@/data/exams/viajeros_almeria_septiembre_2024.json"),
  viajeros_almeria_septiembre_2025: () => import("@/data/exams/viajeros_almeria_septiembre_2025.json"),
  viajeros_cadiz_enero_2024: () => import("@/data/exams/viajeros_cadiz_enero_2024.json"),
  viajeros_cadiz_enero_2025: () => import("@/data/exams/viajeros_cadiz_enero_2025.json"),
  viajeros_cadiz_enero_2026: () => import("@/data/exams/viajeros_cadiz_enero_2026.json"),
  viajeros_cadiz_julio_2024: () => import("@/data/exams/viajeros_cadiz_julio_2024.json"),
  viajeros_cadiz_julio_2025: () => import("@/data/exams/viajeros_cadiz_julio_2025.json"),
  viajeros_cadiz_julio_2026: () => import("@/data/exams/viajeros_cadiz_julio_2026.json"),
  viajeros_cadiz_marzo_2024: () => import("@/data/exams/viajeros_cadiz_marzo_2024.json"),
  viajeros_cadiz_marzo_2025: () => import("@/data/exams/viajeros_cadiz_marzo_2025.json"),
  viajeros_cadiz_marzo_2026: () => import("@/data/exams/viajeros_cadiz_marzo_2026.json"),
  viajeros_cadiz_mayo_2024: () => import("@/data/exams/viajeros_cadiz_mayo_2024.json"),
  viajeros_cadiz_mayo_2025: () => import("@/data/exams/viajeros_cadiz_mayo_2025.json"),
  viajeros_cadiz_mayo_2026: () => import("@/data/exams/viajeros_cadiz_mayo_2026.json"),
  viajeros_cadiz_noviembre_2024: () => import("@/data/exams/viajeros_cadiz_noviembre_2024.json"),
  viajeros_cadiz_septiembre_2024: () => import("@/data/exams/viajeros_cadiz_septiembre_2024.json"),
  viajeros_cantabria_abril_2025: () => import("@/data/exams/viajeros_cantabria_abril_2025.json"),
  viajeros_cantabria_abril_2026: () => import("@/data/exams/viajeros_cantabria_abril_2026.json"),
  viajeros_cantabria_agosto_2025: () => import("@/data/exams/viajeros_cantabria_agosto_2025.json"),
  viajeros_cantabria_diciembre_2025: () => import("@/data/exams/viajeros_cantabria_diciembre_2025.json"),
  viajeros_cantabria_febrero_2025: () => import("@/data/exams/viajeros_cantabria_febrero_2025.json"),
  viajeros_cantabria_febrero_2026: () => import("@/data/exams/viajeros_cantabria_febrero_2026.json"),
  viajeros_cantabria_junio_2025: () => import("@/data/exams/viajeros_cantabria_junio_2025.json"),
  viajeros_cantabria_junio_2026: () => import("@/data/exams/viajeros_cantabria_junio_2026.json"),
  viajeros_cantabria_octubre_2025: () => import("@/data/exams/viajeros_cantabria_octubre_2025.json"),
  viajeros_cataluna_enero_2024: () => import("@/data/exams/viajeros_cataluna_enero_2024.json"),
  viajeros_cataluna_enero_2025: () => import("@/data/exams/viajeros_cataluna_enero_2025.json"),
  viajeros_cataluna_enero_2026: () => import("@/data/exams/viajeros_cataluna_enero_2026.json"),
  viajeros_cataluna_julio_2023: () => import("@/data/exams/viajeros_cataluna_julio_2023.json"),
  viajeros_cataluna_julio_2024: () => import("@/data/exams/viajeros_cataluna_julio_2024.json"),
  viajeros_cataluna_julio_2025: () => import("@/data/exams/viajeros_cataluna_julio_2025.json"),
  viajeros_cataluna_julio_2026: () => import("@/data/exams/viajeros_cataluna_julio_2026.json"),
  viajeros_cataluna_marzo_2023: () => import("@/data/exams/viajeros_cataluna_marzo_2023.json"),
  viajeros_cataluna_marzo_2024: () => import("@/data/exams/viajeros_cataluna_marzo_2024.json"),
  viajeros_cataluna_marzo_2025: () => import("@/data/exams/viajeros_cataluna_marzo_2025.json"),
  viajeros_cataluna_marzo_2026: () => import("@/data/exams/viajeros_cataluna_marzo_2026.json"),
  viajeros_cataluna_mayo_2023: () => import("@/data/exams/viajeros_cataluna_mayo_2023.json"),
  viajeros_cataluna_mayo_2024: () => import("@/data/exams/viajeros_cataluna_mayo_2024.json"),
  viajeros_cataluna_mayo_2025: () => import("@/data/exams/viajeros_cataluna_mayo_2025.json"),
  viajeros_cataluna_mayo_2026: () => import("@/data/exams/viajeros_cataluna_mayo_2026.json"),
  viajeros_cataluna_noviembre_2023: () => import("@/data/exams/viajeros_cataluna_noviembre_2023.json"),
  viajeros_cataluna_noviembre_2024: () => import("@/data/exams/viajeros_cataluna_noviembre_2024.json"),
  viajeros_cataluna_noviembre_2025: () => import("@/data/exams/viajeros_cataluna_noviembre_2025.json"),
  viajeros_cataluna_septiembre_2023: () => import("@/data/exams/viajeros_cataluna_septiembre_2023.json"),
  viajeros_cataluna_septiembre_2024: () => import("@/data/exams/viajeros_cataluna_septiembre_2024.json"),
  viajeros_cataluna_septiembre_2025: () => import("@/data/exams/viajeros_cataluna_septiembre_2025.json"),
  viajeros_cordoba_enero_2024: () => import("@/data/exams/viajeros_cordoba_enero_2024.json"),
  viajeros_cordoba_enero_2025: () => import("@/data/exams/viajeros_cordoba_enero_2025.json"),
  viajeros_cordoba_enero_2026: () => import("@/data/exams/viajeros_cordoba_enero_2026.json"),
  viajeros_cordoba_julio_2024: () => import("@/data/exams/viajeros_cordoba_julio_2024.json"),
  viajeros_cordoba_julio_2025: () => import("@/data/exams/viajeros_cordoba_julio_2025.json"),
  viajeros_cordoba_julio_2026: () => import("@/data/exams/viajeros_cordoba_julio_2026.json"),
  viajeros_cordoba_marzo_2024: () => import("@/data/exams/viajeros_cordoba_marzo_2024.json"),
  viajeros_cordoba_marzo_2025: () => import("@/data/exams/viajeros_cordoba_marzo_2025.json"),
  viajeros_cordoba_marzo_2026: () => import("@/data/exams/viajeros_cordoba_marzo_2026.json"),
  viajeros_cordoba_mayo_2024: () => import("@/data/exams/viajeros_cordoba_mayo_2024.json"),
  viajeros_cordoba_mayo_2025: () => import("@/data/exams/viajeros_cordoba_mayo_2025.json"),
  viajeros_cordoba_mayo_2026: () => import("@/data/exams/viajeros_cordoba_mayo_2026.json"),
  viajeros_cordoba_noviembre_2024: () => import("@/data/exams/viajeros_cordoba_noviembre_2024.json"),
  viajeros_cordoba_noviembre_2025: () => import("@/data/exams/viajeros_cordoba_noviembre_2025.json"),
  viajeros_cordoba_septiembre_2024: () => import("@/data/exams/viajeros_cordoba_septiembre_2024.json"),
  viajeros_cordoba_septiembre_2025: () => import("@/data/exams/viajeros_cordoba_septiembre_2025.json"),
  viajeros_galicia_enero_2023: () => import("@/data/exams/viajeros_galicia_enero_2023.json"),
  viajeros_galicia_enero_2024: () => import("@/data/exams/viajeros_galicia_enero_2024.json"),
  viajeros_galicia_enero_2025: () => import("@/data/exams/viajeros_galicia_enero_2025.json"),
  viajeros_galicia_enero_2026: () => import("@/data/exams/viajeros_galicia_enero_2026.json"),
  viajeros_galicia_julio_2023: () => import("@/data/exams/viajeros_galicia_julio_2023.json"),
  viajeros_galicia_julio_2024: () => import("@/data/exams/viajeros_galicia_julio_2024.json"),
  viajeros_galicia_julio_2025: () => import("@/data/exams/viajeros_galicia_julio_2025.json"),
  viajeros_galicia_julio_2026: () => import("@/data/exams/viajeros_galicia_julio_2026.json"),
  viajeros_galicia_junio_2023: () => import("@/data/exams/viajeros_galicia_junio_2023.json"),
  viajeros_galicia_junio_2024: () => import("@/data/exams/viajeros_galicia_junio_2024.json"),
  viajeros_galicia_junio_2026: () => import("@/data/exams/viajeros_galicia_junio_2026.json"),
  viajeros_galicia_marzo_2023: () => import("@/data/exams/viajeros_galicia_marzo_2023.json"),
  viajeros_galicia_marzo_2024: () => import("@/data/exams/viajeros_galicia_marzo_2024.json"),
  viajeros_galicia_marzo_2025: () => import("@/data/exams/viajeros_galicia_marzo_2025.json"),
  viajeros_galicia_marzo_2026: () => import("@/data/exams/viajeros_galicia_marzo_2026.json"),
  viajeros_galicia_mayo_2024: () => import("@/data/exams/viajeros_galicia_mayo_2024.json"),
  viajeros_galicia_mayo_2025: () => import("@/data/exams/viajeros_galicia_mayo_2025.json"),
  viajeros_galicia_mayo_2026: () => import("@/data/exams/viajeros_galicia_mayo_2026.json"),
  viajeros_galicia_noviembre_2023: () => import("@/data/exams/viajeros_galicia_noviembre_2023.json"),
  viajeros_galicia_noviembre_2024: () => import("@/data/exams/viajeros_galicia_noviembre_2024.json"),
  viajeros_galicia_noviembre_2025: () => import("@/data/exams/viajeros_galicia_noviembre_2025.json"),
  viajeros_galicia_octubre_2023: () => import("@/data/exams/viajeros_galicia_octubre_2023.json"),
  viajeros_galicia_octubre_2025: () => import("@/data/exams/viajeros_galicia_octubre_2025.json"),
  viajeros_galicia_septiembre_2023: () => import("@/data/exams/viajeros_galicia_septiembre_2023.json"),
  viajeros_galicia_septiembre_2024: () => import("@/data/exams/viajeros_galicia_septiembre_2024.json"),
  viajeros_galicia_septiembre_2025: () => import("@/data/exams/viajeros_galicia_septiembre_2025.json"),
  viajeros_galicia_septiembre_2026: () => import("@/data/exams/viajeros_galicia_septiembre_2026.json"),
  viajeros_granada_enero_2024: () => import("@/data/exams/viajeros_granada_enero_2024.json"),
  viajeros_granada_enero_2025: () => import("@/data/exams/viajeros_granada_enero_2025.json"),
  viajeros_granada_enero_2026: () => import("@/data/exams/viajeros_granada_enero_2026.json"),
  viajeros_granada_julio_2024: () => import("@/data/exams/viajeros_granada_julio_2024.json"),
  viajeros_granada_julio_2025: () => import("@/data/exams/viajeros_granada_julio_2025.json"),
  viajeros_granada_julio_2026: () => import("@/data/exams/viajeros_granada_julio_2026.json"),
  viajeros_granada_marzo_2024: () => import("@/data/exams/viajeros_granada_marzo_2024.json"),
  viajeros_granada_marzo_2025: () => import("@/data/exams/viajeros_granada_marzo_2025.json"),
  viajeros_granada_marzo_2026: () => import("@/data/exams/viajeros_granada_marzo_2026.json"),
  viajeros_granada_mayo_2024: () => import("@/data/exams/viajeros_granada_mayo_2024.json"),
  viajeros_granada_mayo_2025: () => import("@/data/exams/viajeros_granada_mayo_2025.json"),
  viajeros_granada_mayo_2026: () => import("@/data/exams/viajeros_granada_mayo_2026.json"),
  viajeros_granada_noviembre_2024: () => import("@/data/exams/viajeros_granada_noviembre_2024.json"),
  viajeros_granada_noviembre_2025: () => import("@/data/exams/viajeros_granada_noviembre_2025.json"),
  viajeros_granada_septiembre_2024: () => import("@/data/exams/viajeros_granada_septiembre_2024.json"),
  viajeros_granada_septiembre_2025: () => import("@/data/exams/viajeros_granada_septiembre_2025.json"),
  viajeros_guipuzkoa_enero_2026: () => import("@/data/exams/viajeros_guipuzkoa_enero_2026.json"),
  viajeros_guipuzkoa_julio_2025: () => import("@/data/exams/viajeros_guipuzkoa_julio_2025.json"),
  viajeros_guipuzkoa_julio_2026: () => import("@/data/exams/viajeros_guipuzkoa_julio_2026.json"),
  viajeros_guipuzkoa_marzo_2026: () => import("@/data/exams/viajeros_guipuzkoa_marzo_2026.json"),
  viajeros_guipuzkoa_mayo_2025: () => import("@/data/exams/viajeros_guipuzkoa_mayo_2025.json"),
  viajeros_guipuzkoa_mayo_2026: () => import("@/data/exams/viajeros_guipuzkoa_mayo_2026.json"),
  viajeros_guipuzkoa_noviembre_2025: () => import("@/data/exams/viajeros_guipuzkoa_noviembre_2025.json"),
  viajeros_guipuzkoa_septiembre_2025: () => import("@/data/exams/viajeros_guipuzkoa_septiembre_2025.json"),
  viajeros_huelva_julio_2025: () => import("@/data/exams/viajeros_huelva_julio_2025.json"),
  viajeros_huelva_julio_2026: () => import("@/data/exams/viajeros_huelva_julio_2026.json"),
  viajeros_huelva_mayo_2025: () => import("@/data/exams/viajeros_huelva_mayo_2025.json"),
  viajeros_huelva_noviembre_2025: () => import("@/data/exams/viajeros_huelva_noviembre_2025.json"),
  viajeros_jaen_enero_2024: () => import("@/data/exams/viajeros_jaen_enero_2024.json"),
  viajeros_jaen_enero_2025: () => import("@/data/exams/viajeros_jaen_enero_2025.json"),
  viajeros_jaen_enero_2026: () => import("@/data/exams/viajeros_jaen_enero_2026.json"),
  viajeros_jaen_julio_2024: () => import("@/data/exams/viajeros_jaen_julio_2024.json"),
  viajeros_jaen_julio_2025: () => import("@/data/exams/viajeros_jaen_julio_2025.json"),
  viajeros_jaen_julio_2026: () => import("@/data/exams/viajeros_jaen_julio_2026.json"),
  viajeros_jaen_marzo_2024: () => import("@/data/exams/viajeros_jaen_marzo_2024.json"),
  viajeros_jaen_marzo_2025: () => import("@/data/exams/viajeros_jaen_marzo_2025.json"),
  viajeros_jaen_marzo_2026: () => import("@/data/exams/viajeros_jaen_marzo_2026.json"),
  viajeros_jaen_mayo_2024: () => import("@/data/exams/viajeros_jaen_mayo_2024.json"),
  viajeros_jaen_mayo_2025: () => import("@/data/exams/viajeros_jaen_mayo_2025.json"),
  viajeros_jaen_mayo_2026: () => import("@/data/exams/viajeros_jaen_mayo_2026.json"),
  viajeros_jaen_noviembre_2024: () => import("@/data/exams/viajeros_jaen_noviembre_2024.json"),
  viajeros_jaen_noviembre_2025: () => import("@/data/exams/viajeros_jaen_noviembre_2025.json"),
  viajeros_jaen_septiembre_2024: () => import("@/data/exams/viajeros_jaen_septiembre_2024.json"),
  viajeros_jaen_septiembre_2025: () => import("@/data/exams/viajeros_jaen_septiembre_2025.json"),
  viajeros_malaga_enero_2024: () => import("@/data/exams/viajeros_malaga_enero_2024.json"),
  viajeros_malaga_enero_2025: () => import("@/data/exams/viajeros_malaga_enero_2025.json"),
  viajeros_malaga_enero_2026: () => import("@/data/exams/viajeros_malaga_enero_2026.json"),
  viajeros_malaga_julio_2024: () => import("@/data/exams/viajeros_malaga_julio_2024.json"),
  viajeros_malaga_julio_2025: () => import("@/data/exams/viajeros_malaga_julio_2025.json"),
  viajeros_malaga_julio_2026: () => import("@/data/exams/viajeros_malaga_julio_2026.json"),
  viajeros_malaga_marzo_2024: () => import("@/data/exams/viajeros_malaga_marzo_2024.json"),
  viajeros_malaga_marzo_2025: () => import("@/data/exams/viajeros_malaga_marzo_2025.json"),
  viajeros_malaga_marzo_2026: () => import("@/data/exams/viajeros_malaga_marzo_2026.json"),
  viajeros_malaga_mayo_2024: () => import("@/data/exams/viajeros_malaga_mayo_2024.json"),
  viajeros_malaga_mayo_2025: () => import("@/data/exams/viajeros_malaga_mayo_2025.json"),
  viajeros_malaga_mayo_2026: () => import("@/data/exams/viajeros_malaga_mayo_2026.json"),
  viajeros_malaga_noviembre_2024: () => import("@/data/exams/viajeros_malaga_noviembre_2024.json"),
  viajeros_malaga_septiembre_2024: () => import("@/data/exams/viajeros_malaga_septiembre_2024.json"),
  viajeros_malaga_septiembre_2025: () => import("@/data/exams/viajeros_malaga_septiembre_2025.json"),
  viajeros_sevilla_enero_2024: () => import("@/data/exams/viajeros_sevilla_enero_2024.json"),
  viajeros_sevilla_enero_2025: () => import("@/data/exams/viajeros_sevilla_enero_2025.json"),
  viajeros_sevilla_enero_2026: () => import("@/data/exams/viajeros_sevilla_enero_2026.json"),
  viajeros_sevilla_julio_2024: () => import("@/data/exams/viajeros_sevilla_julio_2024.json"),
  viajeros_sevilla_julio_2025: () => import("@/data/exams/viajeros_sevilla_julio_2025.json"),
  viajeros_sevilla_julio_2026: () => import("@/data/exams/viajeros_sevilla_julio_2026.json"),
  viajeros_sevilla_marzo_2024: () => import("@/data/exams/viajeros_sevilla_marzo_2024.json"),
  viajeros_sevilla_marzo_2025: () => import("@/data/exams/viajeros_sevilla_marzo_2025.json"),
  viajeros_sevilla_marzo_2026: () => import("@/data/exams/viajeros_sevilla_marzo_2026.json"),
  viajeros_sevilla_mayo_2024: () => import("@/data/exams/viajeros_sevilla_mayo_2024.json"),
  viajeros_sevilla_mayo_2025: () => import("@/data/exams/viajeros_sevilla_mayo_2025.json"),
  viajeros_sevilla_mayo_2026: () => import("@/data/exams/viajeros_sevilla_mayo_2026.json"),
  viajeros_sevilla_noviembre_2024: () => import("@/data/exams/viajeros_sevilla_noviembre_2024.json"),
  viajeros_sevilla_noviembre_2025: () => import("@/data/exams/viajeros_sevilla_noviembre_2025.json"),
  viajeros_sevilla_septiembre_2024: () => import("@/data/exams/viajeros_sevilla_septiembre_2024.json"),
  viajeros_sevilla_septiembre_2025: () => import("@/data/exams/viajeros_sevilla_septiembre_2025.json"),
  viajeros_valencia_abril_2025: () => import("@/data/exams/viajeros_valencia_abril_2025.json"),
  viajeros_valencia_enero_2023: () => import("@/data/exams/viajeros_valencia_enero_2023.json"),
  viajeros_valencia_enero_2024: () => import("@/data/exams/viajeros_valencia_enero_2024.json"),
  viajeros_valencia_febrero_2025: () => import("@/data/exams/viajeros_valencia_febrero_2025.json"),
  viajeros_valencia_febrero_2026: () => import("@/data/exams/viajeros_valencia_febrero_2026.json"),
  viajeros_valencia_julio_2023: () => import("@/data/exams/viajeros_valencia_julio_2023.json"),
  viajeros_valencia_julio_2024: () => import("@/data/exams/viajeros_valencia_julio_2024.json"),
  viajeros_valencia_julio_2025: () => import("@/data/exams/viajeros_valencia_julio_2025.json"),
  viajeros_valencia_julio_2026: () => import("@/data/exams/viajeros_valencia_julio_2026.json"),
  viajeros_valencia_marzo_2023: () => import("@/data/exams/viajeros_valencia_marzo_2023.json"),
  viajeros_valencia_marzo_2024: () => import("@/data/exams/viajeros_valencia_marzo_2024.json"),
  viajeros_valencia_marzo_2026: () => import("@/data/exams/viajeros_valencia_marzo_2026.json"),
  viajeros_valencia_mayo_2023: () => import("@/data/exams/viajeros_valencia_mayo_2023.json"),
  viajeros_valencia_mayo_2024: () => import("@/data/exams/viajeros_valencia_mayo_2024.json"),
  viajeros_valencia_mayo_2025: () => import("@/data/exams/viajeros_valencia_mayo_2025.json"),
  viajeros_valencia_mayo_2026: () => import("@/data/exams/viajeros_valencia_mayo_2026.json"),
  viajeros_valencia_noviembre_2023: () => import("@/data/exams/viajeros_valencia_noviembre_2023.json"),
  viajeros_valencia_noviembre_2024: () => import("@/data/exams/viajeros_valencia_noviembre_2024.json"),
  viajeros_valencia_noviembre_2025: () => import("@/data/exams/viajeros_valencia_noviembre_2025.json"),
  viajeros_valencia_septiembre_2023: () => import("@/data/exams/viajeros_valencia_septiembre_2023.json"),
  viajeros_valencia_septiembre_2024: () => import("@/data/exams/viajeros_valencia_septiembre_2024.json"),
  viajeros_valencia_septiembre_2025: () => import("@/data/exams/viajeros_valencia_septiembre_2025.json"),
};

